services:
  # =============================================================================
  # PostgreSQL Database
  # =============================================================================
  postgres:
    container_name: colmena-db
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  # =============================================================================
  # Colmena API Application
  # =============================================================================
  api:
    container_name: colmena-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      NODE_ENV: production
      PORT: ${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    working_dir: /app
    depends_on:
      - postgres

# =============================================================================
# Volumes
# =============================================================================
volumes:
  postgres_data: